### ISSUE TITLE
Gracefully degrade large file support

### ISSUE THREAD

**Issue by bryanchriswhite** [LeastAuthority/MyFileTransfer#37]
### Background

Until we are able to schedule work on root cause analysis of the issues we experience with large file transfers, we want to gracefully degrade when asked to transfer files larger than currently known limitations. We want to inform users that we are unable to currently support files above a certain size but intend to support a larger limit at some future milestone.

### Acceptance Criteria

When a file is selected which is over 200MB in size:
1. a modal error dialog appears (copy/design needed)
2. the filename and size are not updated in the UI (it should look as if nothing happened after the dialog is dismissed)

**Comment by on-ba** [comment]
Suggested copy: 

> **Large file sizes: coming soon** 
> 
> In this development stage, this product only supports file sizes of up to 200 MB. 
> 
> Please select a different file.

**Comment by bryanchriswhite** [comment]
![Screenshot from 2021-09-17 09-09-32](https://user-images.githubusercontent.com/600733/133742196-1aa6ff91-bbf3-49c0-bb4b-a6731d0c69e0.png)
